apiVersion: v1
kind: Service
metadata:
  name: gorrashop-backend
  namespace: gorrashop
  labels:
    app: gorrashop-backend
spec:
  selector:
    app: gorrashop-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
