apiVersion: v1
kind: Service
metadata:
  name: gorrashop-frontend
  namespace: gorrashop
  labels:
    app: gorrashop-frontend
spec:
  selector:
    app: gorrashop-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
