---
apiVersion: v1
kind: Namespace
metadata:
  name: gorrashop
  labels:
    app.kubernetes.io/part-of: gorrashop

---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: gorrashop-observability
