---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorrashop-backend
  namespace: gorrashop
spec:
  template:
    spec:
      containers:
        - name: gorrashop-backend
          env:
            # El Datadog Agent como DaemonSet expone OTLP via hostPort
            # Usamos status.hostIP para apuntar al Agent del mismo nodo
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: DD_ENV
              value: "lab"
            - name: DD_SERVICE
              value: "gorrashop-backend"
            - name: DD_VERSION
              value: "1.0.0"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorrashop-frontend
  namespace: gorrashop
spec:
  template:
    spec:
      containers:
        - name: gorrashop-frontend
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: DD_ENV
              value: "lab"
            - name: DD_SERVICE
              value: "gorrashop-frontend"
