spec:
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/js-lib.version: "v5"
    spec:
      containers:
        - name: gorrashop-frontend
          env:
            - name: OBSERVABILITY_ENABLED
              value: "false"
            - name: DD_ENV
              value: "lab"
            - name: DD_SERVICE
              value: "gorrashop-frontend"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1.0"
