spec:
  template:
    metadata:
      labels:
        scenario: "2"
        pipeline: dd-sdk-ddot
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/dotnet-lib.version: "v2"
    spec:
      containers:
        - name: gorrashop-backend
          env:
            - name: OBSERVABILITY_ENABLED
              value: "false"
            - name: DD_ENV
              value: "scenario-2-ddsdk-ddot"
            - name: DD_SERVICE
              value: "gorrashop-backend"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TAGS
              value: "scenario:2,pipeline:dd-sdk-ddot"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1.0"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_GIT_COMMIT_SHA
              value: "879150c2b0500c20335c69e6756680ab200ae731"
            - name: DD_GIT_REPOSITORY_URL
              value: "https://github.com/samgarcia-ddog/Datadog---Opentelemetry---DDOT"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=scenario-2-ddsdk-ddot,scenario=2,pipeline=dd-sdk-ddot"
